doctrine_migrations:
    dir_name:                           "%kernel.root_dir%/DoctrineMigrations"
    name:                               Application Migrations
    namespace:                          Application\Migrations
    table_name:                         migration_versions
