fos_user:
    db_driver:                          orm
    firewall_name:                      admin
    from_email:
        address:                        "%mailer_user%"
        sender_name:                    "%mailer_user%"
    user_class:                         JamboBundle\Entity\User