JamboBundle\Entity\Patrol:
    options:
        collate:                        utf8_general_ci
    repositoryClass:                    JamboBundle\Entity\Repository\PatrolRepository
    table:                              patrol
    type:                               entity

    id:
        id:
            generator:
                strategy:               AUTO
            type:                       integer
    fields:
        name:
            length:                     50
            type:                       string
        status:
            type:                       smallint
        activationHash:
            length:                     32
            name:                       activation_hash
            options:
                fixed:                  true
            type:                       string
            unique:                     true
        districtId:
            name:                       district_id
            options:
                unsigned:               true
            type:                       smallint
        methodologyGroupId:
            name:                       methodology_group_id
            options:
                unsigned:               true
            type:                       smallint
        comments:
            length:                     255
            nullable:                   true
            type:                       string
        createdAt:
            name:                       created_at
            type:                       datetime
        updatedAt:
            name:                       updated_at
            type:                       datetime

    manyToOne:
        troop:
            inversedBy:                 patrols
            targetEntity:               JamboBundle\Entity\Troop
    oneToOne:
        leader:
            targetEntity:               JamboBundle\Entity\Participant
    oneToMany:
        members:
            cascade:
                -                       persist
            mappedBy:                   patrol
            targetEntity:               JamboBundle\Entity\Participant

    lifecycleCallbacks:
        postLoad:
            -                           initializeCollections
