registration_patrol_form:
    defaults:
        _controller:                    JamboBundle:Registration:patrolForm
    methods:                            [GET|POST]
    path:                               /troop/{troopHash}/patrol
    requirements:
        troopHash:                      "[0-9a-f]{32}$"
