imports:
    - resource:                         config.yml

    - resource:                         bundles/doctrine_migrations.yml

assetic:
    use_controller:                     true

framework:
    router:
        resource:                       "%kernel.project_dir%/app/config/routing_dev.yml"
        strict_requirements:            true
    profiler:
        only_exceptions:                false

monolog:
    handlers:
        main:
            channels:
                -                       "!event"
            level:                      debug
            path:                       "%kernel.logs_dir%/%kernel.environment%.log"
            type:                       stream
        console:
            channels:
                -                       "!console"
                -                       "!doctrine"
                -                       "!event"
            process_psr_3_messages:     false
            type:                       console
        # To follow logs in real time, execute the following command:
        # `bin/console server:log -vv`
        server_log:
            host:                       127.0.0.1:9911
            process_psr_3_messages:     false
            type:                       server_log
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
#        chromephp:
#            level:                      info
#            type:                       chromephp
#        firephp:
#            level:                      info
#            type:                       firephp

web_profiler:
    intercept_redirects:                false
    toolbar:                            true
