imports:
    - resource:                         parameters.yml
    - resource:                         security.yml

    - resource:                         bundles/assetic.yml
    - resource:                         bundles/doctrine.yml
    - resource:                         bundles/fos_user.yml
    - resource:                         bundles/framework.yml
    - resource:                         bundles/jms_i18n_routing.yml
    - resource:                         bundles/jms_translation.yml
    - resource:                         bundles/swiftmailer.yml
    - resource:                         bundles/twig.yml

    - resource:                         "@JamboBundle/Resources/config/repositories.yml"
    - resource:                         "@JamboBundle/Resources/config/services.yml"

parameters:
    assets_version:                     17092901
    locale:                             en
    locales:
        -                               en
        -                               pl
    locales_pattern:                    (en|pl)
    requires_channel:                   http

    jambo.admin.pack_size:              20
    jambo.age_limit.adult:              18
    jambo.age_limit.date:               "2018-08-06"
    jambo.age_limit.max:                120
    jambo.age_limit.min:                6
    jambo.default_prefix:               "+48"
    jambo.email.reply_to:               gdansk2018@krakowska.zhp.pl
    jambo.facebook_event:
        en:                             https://www.facebook.com/events/126759104607920
        pl:                             https://www.facebook.com/events/126759104607920
    jambo.mailer_locale:                pl
    jambo.main_page:
        rules_participant:
            en:                         /regulamin
            pl:                         /regulamin
        url:
            en:                         http://gdansk2018.krakowska.zhp.pl
            pl:                         http://gdansk2018.krakowska.zhp.pl
    jambo.region_id:                    12
    jambo.participant_limit.max:        10
    jambo.participant_limit.min:        10
    jambo.patrol_limit:                 4
    jambo.time_limit.participants:      "2018-01-01 00:00:00"
    jambo.troop_limit:                  10
