registration_success:
    defaults:
        _controller:                    JamboBundle:Registration:success
    methods:                            [GET]
    path:                               /success
