JamboBundle\Entity\Participant:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: pesel
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        firstName:
            - Length:
                max:                    50
                min:                    2
            - NotBlank:                 ~
        lastName:
            - Length:
                max:                    50
                min:                    2
            - NotBlank:                 ~
        address:
            - Length:
                max:                    255
                min:                    10
            - NotBlank:                 ~
        phone:
            - Length:
                max:                    15
                min:                    8
            - NotBlank:                 ~
            - Regex:
                pattern:                "/^[0-9 \\(\\)\\+-]{8,15}$/"
        email:
            - Email:                    ~
            - Length:
                max:                    40
                min:                    3
            - NotBlank:                 ~
        pesel:
            - JamboBundle\Validator\Constraints\ContainsPesel: ~
        guardianName:
            - Length:
                max:                    100
                min:                    2
            - NotBlank:                 ~
        guardianPhone:
            - Length:
                max:                    15
                min:                    8
            - NotBlank:                 ~
            - Regex:
                pattern:                "/^[0-9 \\(\\)\\+-]{8,15}$/"
        specialDiet:
            - Length:
                max:                    255
        comments:
            - Length:
                max:                    255
