registration_troop_form:
    defaults:
        _controller:                    JamboBundle:Registration:troopForm
    methods:                            [GET|POST]
    path:                               /troop
