admin_participant_edit:
    defaults:
        _controller:                    JamboBundle:Admin/Participant:edit
    methods:                            [GET|POST]
    path:                               /admin/participant/{id}/edit
    requirements:
        id:                             \d+
